// Product Database with proper images
const products = [
    // SENSORS
    { id: 1, name: "Thermistor", 
        price: 10, category: "sensors", 
        description: "Temperature sensitive resistor", 
        image: "images/thermistor.png.png " },
        
    { id: 2, name: "DHT11", price: 120, category: "sensors", description: "Digital temperature & humidity sensor", image: "image/DHT11.png" },
    { id: 3, name: "DS18B20", price: 100, category: "sensors", description: "Waterproof temperature sensor", image: "image/ds18b20.png.png " },
    { id: 4, name: "LM35", price: 100, category: "sensors", description: "Precision temperature sensor", image: "images/lm35.png.png " },
    { id: 5, name: "DHT22", price: 170, category: "sensors", description: "High precision temp & humidity sensor", image: "image/DHT22.png.png" },
    { id: 6, name: "MQ2", price: 140, category: "sensors", description: "Gas & smoke detection sensor", image: "images/MQ2.png.png" },
    { id: 7, name: "MQ135", price: 170, category: "sensors", description: "Air quality sensor module", image: "images/MQ135.png.png" },
    { id: 7, name: "MQ3", price: 170, category: "sensors", description: "alcohol sensor module", image: "image/MQ3.jpg" },
    { id: 8, name: "LDR Module", price: 60, category: "sensors", description: "Light intensity detection module", image: "images/LDR.png.png" },
    { id: 9, name: "IR Sensor", price: 50, category: "sensors", description: "Infrared obstacle detection sensor", image: "image/IR.png.png" },
    { id: 10, name: "Color Sensor", price: 450, category: "sensors", description: "RGB color detection module", image: "image/color.png.png" },
    { id: 11, name: "Sound & Voice Sensor", price: 80, category: "sensors", description: "Sound detection module", image: "images/sound.png.png" },
    { id: 12, name: "Vibration Sensor", price: 80, category: "sensors", description: "Vibration & shock detection", image: "images/vibration.png.png" },
    { id: 13, name: "Ultrasonic Sensor", price: 90, category: "sensors", description: "HC-SR04 distance sensor", image: "images/ultrasonic.png.png" },
    { id: 14, name: "Soil Moisture Sensor", price: 80, category: "sensors", description: "Moisture detection for plants", image: "images/soil_moisture.png.png" },
    { id: 15, name: "Touch Sensor", price: 40, category: "sensors", description: "Capacitive touch module", image: "images/touch.png.png" },
    { id: 16, name: "Fingerprint Sensor", price: 1050, category: "sensors", description: "Biometric fingerprint module", image: "image/fingerprint.png.png" },
    { id: 17, name: "RFID Module", price: 150, category: "sensors", description: "RF identification reader", image: "images/RFID.png.png" },
    { id: 18, name: "Rain Sensor", price: 80, category: "sensors", description: "Rainfall detection module", image: "images/rain.png.png" },
    { id: 19, name: "IR Receiver with Remote", price: 70, category: "sensors", description: "IR receiver + remote control", image: "image/ir_receiver.png.png" },
    { id: 20, name: "MPU6050", price: 250, category: "sensors", description: "6-axis gyroscope & accelerometer", image: "images/mpu6050.png" },
    { id: 21, name: "PIR Sensor", price: 100, category: "sensors", description: "Motion detection sensor", image: "images/pir.png" },
    { id: 22, name: "Eye Blink Sensor", price: 200, category: "sensors", description: "Eye blink detection module", image: "image/eyeblink.png" },
    { id: 23, name: "Voltage Sensor", price: 170, category: "sensors", description: "DC voltage measurement module", image: "images/voltagesensor (1).png" },
    { id: 24, name: "Current Sensor", price: 150, category: "sensors", description: "ACS712 current sensor", image: "image/current.png" },
    
    // MICROCONTROLLERS
    { id: 25, name: "Arduino Uno SMD", price: 300, category: "microcontrollers", description: "Arduino Uno SMD (with cable)", image: "image/arduinosmd.png.png" },
    { id: 101, name: "Arduino Nano", price: 300, category: "microcontrollers", description: "Arduino nano (with cable)", image: "image/arduinonano.webp" },
    { id: 26, name: "Arduino Uno DIP", price: 550, category: "microcontrollers", description: "Arduino Uno DIP (with cable)", image: "image/arduinodip.png.png" },
    { id: 27, name: "ESP32", price: 390, category: "microcontrollers", description: "WiFi & Bluetooth dev board", image: "image/esp32.png.png" },
    { id: 102, name: "ESP32cam", price: 900, category: "microcontrollers", description: "esp with good quality camera(with programmer)", image: "image/esp32cam.png" },
    { id: 28, name: "ESP8266", price: 350, category: "microcontrollers", description: "WiFi development board", image: "image/esp8266.png.png" },
    { id: 29, name: "ESP-01", price: 280, category: "microcontrollers", description: "ESP-01 WiFi (with programmer)", image: "image/esp01.png.png" },
    { id: 30, name: "XIAO ESP32 C3", price: 650, category: "microcontrollers", description: "Compact ESP32-C3 board", image: "images/xiao.png.png" },
    { id: 31, name: "Raspberry Pi Pico", price: 350, category: "microcontrollers", description: "RP2040 microcontroller", image: "images/pico.png.png" },
    { id: 32, name: "Raspberry Pi Pico W", price: 600, category: "microcontrollers", description: "Pico with WiFi & Bluetooth", image: "images/picow.png.png" },
    { id: 33, name: "Raspberry Pi Zero 2 W", price: 1600, category: "microcontrollers", description: "Zero 2 with WiFi & BT", image: "images/raspbarry02w.png.png" },
    { id: 34, name: "Raspberry Pi 4 (4GB)", price: 6000, category: "microcontrollers", description: "Pi 4 Model B - 4GB RAM", image: "images/raspbarrypi4,png.png" },
    { id: 35, name: "Raspberry Pi 4 (8GB)", price: 6800, category: "microcontrollers", description: "Pi 4 Model B - 8GB RAM", image: "images/raspbarrypi4,png.png" },
    { id: 36, name: "Raspberry Pi 5 (4GB)", price: 6200, category: "microcontrollers", description: "Latest Pi 5 - 4GB RAM", image: "images/raspbarrypi5.png.png" },
    { id: 37, name: "Raspberry Pi 5 (8GB)", price: 7200, category: "microcontrollers", description: "Latest Pi 5 - 8GB RAM", image: "images/raspbarrypi5.png.png" },
    { id: 38, name: "STM32 Blue Pill", price: 400, category: "microcontrollers", description: "STM32 board (with programmer)", image: "images/stm32.png.png" },
    { id: 39, name: "VC 02", price: 850, category: "microcontrollers", description: "Voice control module", image: "images/vc02.png.png" },
    { id: 89, name: "ATtiny85 Chip", price: 200, category: "microcontrollers", description: "ATtiny85 microcontroller", image: "image/attiny.png.png" },
    { id: 90, name: "8051 Chip", price: 130, category: "microcontrollers", description: "AT89C51 microcontroller", image: "image/8051.png.png" },
    { id: 82, name: "Arduino Cable", price: 60, category: "microcontrollers", description: "USB A to B cable", image: "image/cable.png.png" },
    { id: 83, name: "ESP32 Cable", price: 60, category: "microcontrollers", description: "Micro USB cable", image: "image/cable.png.png" },
    { id: 84, name: "Nano Cable", price: 60, category: "microcontrollers", description: "Mini USB cable", image: "image/cable.png.png" },
   
    // DISPLAYS
    { id: 40, name: "LCD 16x2", price: 120, category: "displays", description: "16x2 character LCD display", image: "images/lcd.png.png " },
    { id: 41, name: "LCD with I2C", price: 220, category: "displays", description: "16x2 LCD with I2C adapter", image: "images/lcd12c.png.png" },
    { id: 42, name: "OLED Display", price: 390, category: "displays", description: "0.96\" OLED I2C display", image: "images/oled.png.png" },
    { id: 98, name: "Digital Volt/Amp Meter", price: 180, category: "displays", description: "Digital voltmeter ammeter", image: "image/digital.png.png" },
    { id: 99, name: "Segment Volt Meter", price: 140, category: "displays", description: "7-segment voltmeter", image: "images/segment.png.png" },

    // BOARDS
    { id: 43, name: "Breadboard", price: 90, category: "boards", description: "Full size breadboard 830 points", image: "image/breadboard.png.png" },
    { id: 44, name: "Half Breadboard", price: 70, category: "boards", description: "Half size breadboard 400 points", image: "images/smallboard.png.png" },
    { id: 45, name: "Mini Breadboard", price: 40, category: "boards", description: "Mini breadboard 170 points", image: "images/miniboard.png.png" },
    { id: 46, name: "Zero PCB", price: 90, category: "boards", description: "General purpose PCB board", image: "images/zero.png.png" },
    { id: 47, name: "Copper Sheet", price: 200, category: "boards", description: "Copper clad PCB sheet", image: "image/copper.png.png" },
    { id: 68, name: "Solar Panel 5V", price: 100, category: "boards", description: "5V solar panel", image: "images/solar.png.png" },
    { id: 69, name: "Solar Panel 12V-3W", price: 350, category: "boards", description: "12V 3W solar panel", image: "images/solar12.png.png" },
    { id: 70, name: "Solar Panel 12V-5W", price: 500, category: "boards", description: "12V 5W solar panel", image: "images/solar12.png.png" },
    { id: 80, name: "3x4 Keyboard", price: 80, category: "boards", description: "3x4 matrix keypad", image: "image/3x4.png.png" },
    { id: 81, name: "4x4 Keyboard", price: 90, category: "boards", description: "4x4 matrix keypad", image: "image/4x4.png.png" },

    // MODULES
    { id: 48, name: "Motor Driver 4 Channel", price: 170, category: "modules", description: "L298N 4-channel driver", image: "image/4driver.png.png" },
    { id: 49, name: "Motor Driver 2 Channel", price: 150, category: "modules", description: "L298N 2-channel driver", image: "image/2driver,png.png" },
    { id: 50, name: "Small Motor Driver", price: 250, category: "modules", description: "Compact motor driver", image: "images/smalldriver.png.png" },
    { id: 51, name: "Buck Converter", price: 80, category: "modules", description: "Step-down DC-DC converter", image: "image/buck.png.png" },
    { id: 52, name: "Boost Converter", price: 120, category: "modules", description: "Step-up DC-DC converter", image: "image/boost,png.png" },
    { id: 53, name: "Remote Car Module", price: 190, category: "modules", description: "RF remote control module", image: "image/carmodule.png.png" },
    { id: 54, name: "Servo Driver 16 Channel", price: 300, category: "modules", description: "16-channel servo driver", image: "image/16channel.png.png" },
    { id: 55, name: "LoRa Module", price: 650, category: "modules", description: "Long range wireless module", image: "images/lora.png.png" },
    { id: 56, name: "nRF24L01 Antenna", price: 250, category: "modules", description: "2.4GHz wireless transceiver", image: "image/antenna.png.png" },
    { id: 57, name: "NEO GPS 6M", price: 290, category: "modules", description: "GPS module with antenna", image: "images/neo.png.png" },
    { id: 58, name: "C Type Charger Module", price: 60, category: "modules", description: "USB Type-C charging module", image: "images/typec.png.png" },
    { id: 94, name: "RF433 Module", price: 90, category: "modules", description: "433MHz RF TX/RX module", image: "images/rf.png.png" },
    { id: 95, name: "BMS 3S/20A", price: 150, category: "modules", description: "Battery management system", image: "image/bms.png.png" },
    { id: 75, name: "Joystick Module", price: 80, category: "modules", description: "Analog joystick controller", image: "image/joy.png.png" },
    { id: 76, name: "5V Relay", price: 70, category: "modules", description: "Single channel relay", image: "images/relay.png.png" },
    { id: 77, name: "4 Channel Relay", price: 220, category: "modules", description: "4-channel relay module", image: "image/4relay.png.png" },
    { id: 87, name: "12V Adaptor", price: 190, category: "modules", description: "12V DC power adapter 2A", image: "image/adaptor.png.png" },
    { id: 67, name: "Jumper Cables", price: 80, category: "modules", description: "M-M, M-F jumper wires bunch", image: "image/jumper.png.png" },
    { id: 65, name: "HC-05", price: 270, category: "modules", description: "Bluetooth master/slave module", image: "image/hc05.png.png" },
    { id: 66, name: "HC-06", price: 300, category: "modules", description: "Bluetooth slave module", image: "image/hc06.png.png" },
    { id: 111, name: "solenoid lock", price: 350, category: "modules", description: "solenoid lock for smart lock systems", image: "image/solenoid.jpg" },
    // BATTERIES
    { id: 59, name: "Li-ion Battery", price: 80, category: "batteries", description: "18650 rechargeable battery", image: "image/battery.png.png" },
    { id: 60, name: "Single Battery Holder", price: 30, category: "batteries", description: "Single AA/AAA holder", image: "image/1holder.png.png" },
    { id: 61, name: "2 Battery Holder", price: 50, category: "batteries", description: "Dual AA/AAA holder", image: "image/2holder.png.png" },
    { id: 62, name: "4 Battery Holder", price: 80, category: "batteries", description: "Quad AA/AAA holder", image: "image/4holder.png.png" },
    { id: 63, name: "HW Battery", price: 25, category: "batteries", description: "High watt battery", image: "image/hw (1).png " },
    { id: 64, name: "Car chassis", price: 550, category: "batteries", description: "Robot car chassis kit", image: "image/car.png.png" },
    { id: 91, name: "BO Motor", price: 70, category: "batteries", description: "Battery operated DC motor (ONLY ONE)", image: "image/bomotor.png.png" },
    { id: 92, name: "Wheel", price: 30, category: "batteries", description: "Robot wheel for BO motor ", image: "images/wheel.png" },
    { id: 108, name: "servo", price: 110, category: "batteries", description: "servo motor for pwm control ", image: "image/servo.jpg" },
    { id: 109, name: "dc motor", price: 15, category: "batteries", description: "small dc motor ", image: "image/motor.jpg" },
    { id: 110, name: "pump motor", price: 140, category: "batteries", description: "pump motor for water pumping with pipe ", image: "image/pump motor.jpg" },
    // TOOLS
    { id: 71, name: "Drill Chuck", price: 200, category: "Tools", description: "Mini drill chuck", image: "image/chuck.png.png" },
    { id: 72, name: "Soldering Iron", price: 150, category: "Tools", description: "30W soldering iron", image: "images/solder.png.png" },
    { id: 73, name: "Lead & Flux", price: 100, category: "Tools", description: "Solder wire & flux kit", image: "images/lead.png.png" },
    { id: 74, name: "Multimeter", price: 170, category: "Tools", description: "Digital multimeter", image: "images/multimeter.png.png" },
    { id: 85, name: "Glue Gun", price: 250, category: "Tools", description: "Hot glue gun with sticks", image: "image/gun.png.png" },
    { id: 85, name: "12v dc motor", price: 190, category: "Tools", description: "for mini drill", image: "image/bigmotor.webp" },
    
    // ACTIVE COMPONENTS
    { id: 78, name: "Buzzer", price: 25, category: "active components", description: "Active piezo buzzer", image: "image/buzzer.png.png" },
    { id: 93, name: "7805 Voltage Regulator", price: 20, category: "active components", description: "5V voltage regulator IC", image: "image/7805.png.png" },
    { id: 97, name: "IC 555 Timer", price: 60, category: "active components", description: "NE555 timer IC with base", image: "image/555.png.png" },
    { id: 103, name: "IRFZ44 MOSFET", price: 25, category: "active components", description: "N-channel power MOSFET", image: "images/mosfet.png.png" },
    { id: 104, name: "BJT transistor", price: 5, category: "active components", description: "PNP transistor", image: "image/bc557.jpg" },
    { id: 105, name: "BJT transistor", price: 5, category: "active components", description: "NPN transistor", image: "image/bc547.jpg" },
    { id: 112, name: "1N4007", price: 7, category: "active components", description: "PN junction diode", image: "image/diode.jpg" },
    { id: 113, name: "1N4148", price: 7, category: "active components", description: "zener diode", image: "image/zener.jpg" },
    { id: 114, name: "bridge rectifier", price: 20, category: "active components", description: "rectifier for AC to DC", image: "image/rectifier.jpg" },
    
    
    // EXCLUSIVE PRODUCTS
    { id: 79, name: "Resistor", price: 3, category: "passive components", description: "Carbon film resistor", image: "images/resistor.png" },
    { id: 106, name: "capacitor", price: 5, category: "passive components", description: "1 to 100 microfarad capacitors", image: "image/100capacitor.webp" },
    { id: 107, name: "capacitor", price: 15, category: "passive components", description: "100 to 1000 microfarad capacitors", image: "image/1000capacitor.webp" },
    { id: 86, name: "Switch", price: 10, category: "passive components", description: "SPDT toggle switch", image: "images/switch.png.png" },
    { id: 88, name: "Push Button", price: 7, category: "passive components", description: "Tactile push button", image: "images/push.png.png" },
    { id: 96, name: "Bug Strip", price: 15, category: "passive components", description: "PCB terminal connector (PER STRIP)", image: "image/female.png.png" },
]